gamma: 0.98
seed: 42

train:
  batch_size: 32
  soft_update: True
  epochs: 250
  episodes: 300
  env_steps: 1
  learn_steps: 100000

env:
  name: CarFollowing
  max_v: 100
  max_g: 200
  delta_t: 0.3
  policy_memory: 10000
  expert_memory: 10000

method:
  type: iq
  loss: value
  tanh: False
  regularize: True
  div: chi
  alpha: 3

agent:
  name: softq
  class: agent.softq.SoftQ
  obs_dim: 0 # To be updated after loading the environment
  action_dim: 9 # To be updated after loading the environment
  critic_cfg:
    _target_: agent.softq_models.SimpleQNetwork
    obs_dim: 0
    action_dim: 9
  critic_lr: 2e-5
  critic_betas: [0.9, 0.999]
  init_temp: 0.5

q_net:
  _target_: agent.softq_models.SimpleQNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
