gamma: 0.97
seed: 42
only_expert_states: False

train:
  epochs: 100
  episodes: 300
  env_steps: 200
  learn_steps: 5000

env:
  name: CarFollowing
  max_v: 30
  max_g: 100
  max_a: 0.05
  delta_t: 0.1
  policy_memory: 5000
  expert_memory: 5000

method:
  type: iq
  loss: value
  constrain: False
  grad_pen: False
  tanh: False
  regularize: True
  div: chi
  alpha: 5

agent:
  name: softq
  class: agent.softq.SoftQ
  obs_dim: 0 # To be updated after loading the environment
  action_dim: 5 # To be updated after loading the environment
  critic_cfg:
    _target_: agent.softq_models.SimpleQNetwork
    obs_dim: 0
    action_dim: 5
  critic_lr: 2e-3
  critic_betas: [0.9, 0.999]
  init_temp: 0.01
  critic_target_update_frequency: 4
  critic_tau: 0.1

q_net:
  _target_: agent.softq_models.SimpleQNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
