exp_name: ""
project_name: ${env.name}

cuda_deterministic: False
device: cpu

gamma: 0.99
seed: 42
pretrain: null

num_seed_steps: 0
only_expert_states: False

train:
  batch: 32
  epochs: 200
  use_target: False
  soft_update: False

env:
  name: CarFollowingEnv
  replay_mem: 25000
  initial_mem: 1280
  eps_steps: 500
  eps_window: 100
  learn_steps: 5e5
  eval_interval: 5e3

method:
  type: iq
  loss: value
  constrain: False
  grad_pen: False
  tanh: False
  regularize: True
  div: chi
  alpha: 0.8
  lambda_gp: 10
  mix_coeff: 1

agent:
  name: softq
  class: agent.softq.SoftQ
  obs_dim: 0 # To be updated after loading the environment
  action_dim: 5 # To be updated after loading the environment
  critic_cfg:
    _target_: agent.softq_models.SimpleQNetwork
    obs_dim: 0
    action_dim: 5
  critic_lr: 2e-4
  critic_betas: [0.9, 0.999]
  init_temp: 0.01
  critic_target_update_frequency: 4
  critic_tau: 0.1

q_net:
  _target_: agent.softq_models.SimpleQNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
