gamma: 0.98
seed: 42
only_expert_states: False

train:
  batch_size: 16
  epochs: 300
  episodes: 30
  sampling_steps: 1
  learn_steps: 5000

env:
  name: FrozenLake
  grid: 8x8
  policy_memory: 100
  expert_memory: 100

method:
  type: iq
  loss: value
  tanh: False
  regularize: True
  div: chi
  alpha: 3

agent:
  name: softq
  class: agent.softq.SoftQ
  obs_dim: 1
  action_dim: 4
  critic_cfg:
    _target_: agent.softq_models.SimpleQNetwork
    obs_dim: 1
    action_dim: 4
  critic_lr: 3e-5
  critic_betas: [0.9, 0.999]
  init_temp: 0.5
  target_update_frequency: 1
  tau: 0.01

q_net:
  _target_: agent.softq_models.SimpleQNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
